/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author danie
 */
public class InterfazMenu extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMenu
     */
    public InterfazMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRegistrp = new javax.swing.JButton();
        Horarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 1920));

        jPanel1.setBackground(new java.awt.Color(246, 171, 7));

        jPanel2.setBackground(new java.awt.Color(161, 15, 42));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRegistrp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-registro-50.png"))); // NOI18N
        jRegistrp.setText("Registro");
        jRegistrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistrpActionPerformed(evt);
            }
        });

        Horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-horarios-externos-negocios-y-trabajo-en-equipo-smashingstocks-mixto-smashing-stocks-50.png"))); // NOI18N
        Horarios.setText("Horarios");
        Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRegistrp)
                    .addComponent(Horarios))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jRegistrp)
                .addGap(31, 31, 31)
                .addComponent(Horarios)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 654, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void abrirRegistro() {
    // Crear el JFrame para el menú principal usando InterfazMenu
    InterfazRegistroTrabajador menuPrincipal = new InterfazRegistroTrabajador();
    menuPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar en pantalla completa
    menuPrincipal.setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    menuPrincipal.setVisible(true); // Hacer visible el JFrame del menú principal

    // Ocultar el JFrame del login
    JFrame loginFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    if (loginFrame != null) {
         this.dispose(); 
    }
      this.dispose(); 

    }
private void abrirhorario() {
    // Crear el JFrame para el menú principal usando InterfazMenu
    InterfazHorarios menuHorario = new InterfazHorarios();
   menuHorario.setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar en pantalla completa
    menuHorario.setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    menuHorario.setVisible(true); // Hacer visible el JFrame del menú principal

    // Ocultar el JFrame del login
    JFrame loginFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    if (loginFrame != null) {
         this.dispose(); 
    }
      this.dispose(); 

    }

    private void jRegistrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistrpActionPerformed
       abrirRegistro();
    }//GEN-LAST:event_jRegistrpActionPerformed

    private void HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorariosActionPerformed
abrirhorario();
    }//GEN-LAST:event_HorariosActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Horarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jRegistrp;
    // End of variables declaration//GEN-END:variables
}
